# Setup

This is the setup stage to pull in the repo and whatever into this and just setting up the paths. Took about 5 hours to figure out.

In [6]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
#%cd /content/drive/MyDrive/DSCI351/Class Project
#!git clone https://github.com/SamiiShabuse/DSCI_Recommender_System_Class_Proj.git
%cd /content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj
!python -m pip install -U pip
!python -m pip install -r requirements.txt

/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj
Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (26.0.1)
Collecting pip
  Using cached pip-26.1.1-py3-none-any.whl.metadata (4.6 kB)
Using cached pip-26.1.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 26.0.1
    Uninstalling pip-26.0.1:
      Successfully uninstalled pip-26.0.1
Successfully installed pip-26.1.1
Collecting pip==26.0.1 (from -r requirements.txt (line 1))
  Using cached pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 26.1.1
    Uninstalling pip-26.1.1:
      Successfully uninstalled pip-26.1.1
Successfully installed pip-26.0.1

In [8]:
import os
os.chdir('/content/drive/MyDrive/DSCI351/Class Project')
print(os.getcwd())

/content/drive/MyDrive/DSCI351/Class Project

In [9]:
!ls "/content/drive/MyDrive/DSCI351/Class Project"

 clean_json_image_mapping.parquet    'Instagram Influencer Dataset'
 Data_Extraction.ipynb		     'Project Proposal.gdoc'
 DSCI_Recommender_System_Class_Proj

In [10]:
from pathlib import Path

DATA_PATH = Path("/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset")
print(DATA_PATH.exists(), DATA_PATH.is_dir())

True True

In [11]:
!find /content/drive -iname "*Instagram*"

/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset
/content/drive/MyDrive/Instagram influencer dataset
/content/drive/MyDrive/DSCI351/Class Project/Instagram Influencer Dataset
find: ‘/content/drive/.Encrypted/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset’: No such file or directory
/content/drive/.Encrypted/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset

In [12]:
items = list(DATA_PATH.iterdir())
[item.name for item in items]

['README.docx',
 'influencers.txt',
 'sample_images.zip',
 'JSON-Image_files_mapping.txt',
 'Post_images',
 'Post_metadata']

In [13]:
POST_IMAGES = DATA_PATH / "Post_images"
POST_METADATA = DATA_PATH / "Post_metadata"
JSON_IMAGE_MAP = DATA_PATH / "JSON-Image_files_mapping.txt"
INFLUENCERS = DATA_PATH / "influencers.txt"
README = DATA_PATH / "README.docx"

In [14]:
print(POST_IMAGES.exists(), POST_IMAGES.is_dir())
print(POST_METADATA.exists(), POST_METADATA.is_dir())
print(JSON_IMAGE_MAP.exists(), JSON_IMAGE_MAP.is_file())
print(INFLUENCERS.exists(), INFLUENCERS.is_file())
print(README.exists(), README.is_file())

True True
True True
True True
True True
True True

In [15]:
print([p.name for p in DATA_PATH.iterdir()][:20])

['README.docx', 'influencers.txt', 'sample_images.zip', 'JSON-Image_files_mapping.txt', 'Post_images', 'Post_metadata']

In [16]:
REPO_CODE = Path("/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj")
print(REPO_CODE.exists(), REPO_CODE.is_dir())

True True

In [17]:
!find /content/drive -iname "*DSCI_Recommender_System_Class_Proj*"

/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj
find: ‘/content/drive/.Encrypted/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset’: No such file or directory
/content/drive/.Encrypted/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj

# Loading in Influencers.txt

Loading in the influencers.txt dataset and cleaning up the dataframe structure took about 30 minutes (I forgot a lot of dataframe manipulation stuff lol)

In [18]:
import pandas as pd

influencers_df = pd.read_csv(INFLUENCERS, sep="\t", engine="python")

print(influencers_df.shape)

(33936, 5)

In [19]:
influencers_df.head()

,Username,Category,#Followers,#Followees,#Posts
0,==============================================...,None,NaN,NaN,NaN
1,makeupbynvs,beauty,1432.0,1089.0,363.0
2,jaquelinevandoski,beauty,137600.0,548.0,569.0
3,anisaartistry,beauty,64644.0,289.0,391.0
4,rubina_muartistry,beauty,496406.0,742.0,887.0

In [20]:
influencers_df.columns = [c.strip() for c in influencers_df.columns]

influencers_df = influencers_df.rename(columns={
    "Username": "influencer",
    "Category": "category",
    "#Followers": "followers",
    "#Followees": "followees",
    "#Posts": "posts"
})

influencers_df.head()

,influencer,category,followers,followees,posts
0,==============================================...,None,NaN,NaN,NaN
1,makeupbynvs,beauty,1432.0,1089.0,363.0
2,jaquelinevandoski,beauty,137600.0,548.0,569.0
3,anisaartistry,beauty,64644.0,289.0,391.0
4,rubina_muartistry,beauty,496406.0,742.0,887.0

In [21]:
fixed_influencers_df = influencers_df.drop(0)
fixed_influencers_df.head()

          influencer category  followers  followees  posts
1        makeupbynvs   beauty     1432.0     1089.0  363.0
2  jaquelinevandoski   beauty   137600.0      548.0  569.0
3      anisaartistry   beauty    64644.0      289.0  391.0
4  rubina_muartistry   beauty   496406.0      742.0  887.0
5        beautyxabbi   beauty     2050.0     1423.0  751.0

# Loading in Json_Image_Mapping

Loading in the Json_Image_Mapping and cleaning up the dataframe structure took about 30 minutes (I forgot a lot of dataframe manipulation stuff lol)

In [22]:
json_mapping_df = pd.read_csv(JSON_IMAGE_MAP, sep="\t", engine="python")

print(json_mapping_df.shape)

(10078910, 1)

In [23]:
json_mapping_df.head()

                                       influencer_name JSON_PostMetadata_file_name Image_file_name
00_rocketgirl 1188140434601337485.info                        ['1188140434601337485.jpg']
              1195378513372308151.info                        ['1195378513372308151.jpg']
              1198311457711775891.info                        ['1198311457711775891.jpg']
              1198947568398164749.info                        ['1198947568398164749.jpg']
              1199462506388578918.info                        ['1199462506388578918.jpg']

In [24]:
import re
import pandas as pd
from tqdm import tqdm #python library to show progress meeters

def load_json_image_mapping(path, max_rows=None):
  rows = []
  current_influencer = None

  with open(path, "r", encoding="utf-8", errors="replace") as f:
    for line_num, line in enumerate(tqdm(f)):
      line = line.strip()

      if not line:
        continue

      # skip the header line and//or separator lines
      if "influencer_name" in line or line.startswith("="):
        continue

      # stop early if just testing
      if max_rows is not None and len(rows) >= max_rows:
        break

      parts = line.split()

      # Case 1: Influencer name is present
      # Ex: 00_rocketgirl 123413241234231423423.info ['1234123412341234.jpg']
      if len(parts) >= 3 and parts[1].endswith(".info"):
        current_influencer = parts[0]
        json_file = parts[1]
        image_file = " ".join(parts[2:])

      # Case 2: influencer name is missing, so just reuse previous influenc
      # Ex: 11234123412341234.info ['123432413241324.jpg']
      elif len(parts) >= 2 and parts[0].endswith(".info"):
        json_file = parts[0]
        image_file = " ".join(parts[1:])

      else:
        continue

      rows.append({
          "influencer_name" : current_influencer,
          "json_file" : json_file,
          "image_file" : image_file
      })

  return pd.DataFrame(rows)

In [25]:
# Testing function ^ on small sample of the data
json_mapping_df_test = load_json_image_mapping(JSON_IMAGE_MAP, max_rows=1000)

print("\nInfo:\n")
print(json_mapping_df_test.shape)
json_mapping_df_test.head(10)

1001it [00:00, 142883.82it/s]

Info:

(1000, 3)

  influencer_name                 json_file                   image_file
0   00_rocketgirl  1188140434601337485.info  ['1188140434601337485.jpg']
1   00_rocketgirl  1195378513372308151.info  ['1195378513372308151.jpg']
2   00_rocketgirl  1198311457711775891.info  ['1198311457711775891.jpg']
3   00_rocketgirl  1198947568398164749.info  ['1198947568398164749.jpg']
4   00_rocketgirl  1199462506388578918.info  ['1199462506388578918.jpg']
5   00_rocketgirl  1207015291657184046.info  ['1207015291657184046.jpg']
6   00_rocketgirl  1208427977485902265.info  ['1208427977485902265.jpg']
7   00_rocketgirl  1208434140696863285.info  ['1208434140696863285.jpg']
8   00_rocketgirl  1208948523948630869.info  ['1208948523948630869.jpg']
9   00_rocketgirl  1210280536441938113.info  ['1210280536441938113.jpg']

In [26]:
json_mapping_df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   influencer_name  1000 non-null   object
 1   json_file        1000 non-null   object
 2   image_file       1000 non-null   object
dtypes: object(3)
memory usage: 23.6+ KB

In [27]:
json_mapping_df_test["influencer_name"].isna().sum()

np.int64(0)

In [28]:
json_mapping_df_test["influencer_name"].nunique()

4

In [29]:
proper_json_mapping_df = load_json_image_mapping(JSON_IMAGE_MAP)

print(proper_json_mapping_df.shape)
proper_json_mapping_df.head()

10078911it [00:26, 375247.90it/s]

(10078910, 3)

  influencer_name                 json_file                   image_file
0   00_rocketgirl  1188140434601337485.info  ['1188140434601337485.jpg']
1   00_rocketgirl  1195378513372308151.info  ['1195378513372308151.jpg']
2   00_rocketgirl  1198311457711775891.info  ['1198311457711775891.jpg']
3   00_rocketgirl  1198947568398164749.info  ['1198947568398164749.jpg']
4   00_rocketgirl  1199462506388578918.info  ['1199462506388578918.jpg']

In [30]:
proper_json_mapping_df["influencer_name"].isna().sum()

np.int64(0)

In [31]:
proper_json_mapping_df["influencer_name"].nunique()

33889

# Saving Cleaned Json Mapping to Folder

Can call this next time to save time from running

In [32]:
# clean_mapping_path = REPO_CODE / "clean_json_image_mapping.parquet"

# proper_json_mapping_df.to_parquet(clean_mapping_path, index=False)

# print("Saved to:", clean_mapping_path)

In [33]:
#json_mapping_df = pd.read_parquet(clean_mapping_path)

In [34]:
proper_json_mapping_df = proper_json_mapping_df.rename(columns={
    "json_file": "json_postmetadata_file_name",
    "image_file": "image_file_name"
})

proper_json_mapping_df.head()

  influencer_name json_postmetadata_file_name              image_file_name
0   00_rocketgirl    1188140434601337485.info  ['1188140434601337485.jpg']
1   00_rocketgirl    1195378513372308151.info  ['1195378513372308151.jpg']
2   00_rocketgirl    1198311457711775891.info  ['1198311457711775891.jpg']
3   00_rocketgirl    1198947568398164749.info  ['1198947568398164749.jpg']
4   00_rocketgirl    1199462506388578918.info  ['1199462506388578918.jpg']

In [35]:
proper_json_mapping_df.duplicated().sum()

np.int64(17982)

In [36]:
proper_json_mapping_df["json_postmetadata_file_name"].duplicated().sum()

np.int64(18010)

# Clean out duplicates

In [37]:
json_mapping_clean = proper_json_mapping_df.copy()

# Remove exact duplicates
json_mapping_clean = json_mapping_clean.drop_duplicates()

# Keep only one row per metadata file
json_mapping_clean = json_mapping_clean.drop_duplicates(
    subset=["json_postmetadata_file_name"],
    keep="first"
)

In [38]:
print("Original Shape:", proper_json_mapping_df.shape)
print("Clean Shape:", json_mapping_clean.shape)

print("Exact duplicates left:", json_mapping_clean.duplicated().sum())
print("Duplicate metadata files left:", json_mapping_clean["json_postmetadata_file_name"].duplicated().sum())

json_mapping_clean.head()

Original Shape: (10078910, 3)
Clean Shape: (10060900, 3)
Exact duplicates left: 0
Duplicate metadata files left: 0

  influencer_name json_postmetadata_file_name              image_file_name
0   00_rocketgirl    1188140434601337485.info  ['1188140434601337485.jpg']
1   00_rocketgirl    1195378513372308151.info  ['1195378513372308151.jpg']
2   00_rocketgirl    1198311457711775891.info  ['1198311457711775891.jpg']
3   00_rocketgirl    1198947568398164749.info  ['1198947568398164749.jpg']
4   00_rocketgirl    1199462506388578918.info  ['1199462506388578918.jpg']

# Use Post_metadata

In [39]:
metadata_files = list(POST_METADATA.rglob("*.info")) + list(POST_METADATA.rglob("*.json"))

print("Metadata files found:", len(metadata_files))
print(len(metadata_files))
print(metadata_files[:5])

Metadata files found: 0
0
[]

In [40]:
print("POST_METADATA path:", POST_METADATA)
print("Exists:", POST_METADATA.exists())
print("Is folder:", POST_METADATA.is_dir())

items = list(POST_METADATA.iterdir())
print("Number of direct items:", len(items))
print("First 20 items:")
for item in items[:20]:
    print(item.name, "| folder:", item.is_dir(), "| file:", item.is_file())

POST_METADATA path: /content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata
Exists: True
Is folder: True
Number of direct items: 19
First 20 items:
posts_info.zip | folder: False | file: True
posts_info.z18 | folder: False | file: True
posts_info.z17 | folder: False | file: True
posts_info.z16 | folder: False | file: True
posts_info.z15 | folder: False | file: True
posts_info.z14 | folder: False | file: True
posts_info.z13 | folder: False | file: True
posts_info.z12 | folder: False | file: True
posts_info.z11 | folder: False | file: True
posts_info.z10 | folder: False | file: True
posts_info.z09 | folder: False | file: True
posts_info.z08 | folder: False | file: True
posts_info.z07 | folder: False | file: True
posts_info.z06 | folder: False | file: True
posts_info.z05 | folder: False | file: True
posts_info.z04 | folder: False | file: True
posts_info.z03 | folder: False | file: True
posts_info.z02 | folder: False | file: True
posts_info.z01 | folder: False | file: True

In [41]:
all_metadata_items = list(POST_METADATA.rglob("*"))

print("Total items inside Post_metadata:", len(all_metadata_items))
print("First 20:")
for item in all_metadata_items[:20]:
    print(item)

Total items inside Post_metadata: 19
First 20:
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.zip
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z18
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z17
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z16
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z15
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z14
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z13
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z12
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z11
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z10
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z09
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z08
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z07
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z06
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z05
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z04
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z03
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z02
/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.z01

In [42]:
!apt-get -qq update
!apt-get -qq install -y p7zip-full

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

In [43]:
POSTS_INFO_ZIP = POST_METADATA / "posts_info.zip"

print(POSTS_INFO_ZIP)
print(POSTS_INFO_ZIP.exists())

/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.zip
True

In [44]:
!df -h

Filesystem      Size  Used Avail Use% Mounted on
overlay         108G   23G   86G  21% /
tmpfs            64M     0   64M   0% /dev
shm             5.7G  4.0K  5.7G   1% /dev/shm
/dev/root       2.0G  1.3G  696M  65% /usr/sbin/docker-init
tmpfs           6.4G  784K  6.4G   1% /var/colab
/dev/sda1       114G   24G   91G  21% /kaggle/input
tmpfs           6.4G     0  6.4G   0% /proc/acpi
tmpfs           6.4G     0  6.4G   0% /proc/scsi
tmpfs           6.4G     0  6.4G   0% /sys/firmware
drive           108G   27G   82G  25% /content/drive

In [45]:
!du -sh "{EXTRACTED_METADATA}" || true

du: cannot access '{EXTRACTED_METADATA}': No such file or directory

# failed extraction

In [46]:
#!7z l "{POSTS_INFO_ZIP}" | head -80

In [47]:
# EXTRACTED_METADATA = REPO_CODE / "Post_metadata_extracted"
# EXTRACTED_METADATA.mkdir(exist_ok=True)

# print(EXTRACTED_METADATA)

In [48]:
#!7z x "{POSTS_INFO_ZIP}" -o"{EXTRACTED_METADATA}" -y

In [49]:
archive_listing_path = REPO_CODE / "posts_info_archive_listing.txt"

# !7z l -slt "{POSTS_INFO_ZIP}" > "{archive_listing_path}"

print("Saved archive listing to:", archive_listing_path)

Saved archive listing to: /content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/posts_info_archive_listing.txt

In [50]:
archive_paths = []

with open(archive_listing_path, "r", encoding="utf-8", errors="replace") as f:
    for line in f:
        line = line.strip()
        if line.startswith("Path = "):
            path = line.replace("Path = ", "")
            if path.endswith(".info") or path.endswith(".json"):
                archive_paths.append(path)

print("Metadata files inside archive:", len(archive_paths))
print(archive_paths[:10])

Metadata files inside archive: 9726219
['info/beckilw_sw-1684125244807239621.info', 'info/archilovers-1966283174661250572.info', 'info/laviniaaioana-1892733406089983442.info', 'info/notjustamumof2-1861977278444228346.info', 'info/thechristinakay-1548033680911884321.info', 'info/jasonnaylor-2018247528004639299.info', 'info/mrthreepiece-1593726884489821885.info', 'info/willows_den-1858788687819702788.info', 'info/uhmlady-1464273234106453793.info', 'info/inesjoly-1718391610176599945.info']

In [53]:
sample_archive_paths = archive_paths[:1000]

sample_list_path = REPO_CODE / "sample_metadata_files_to_extract.txt"

with open(sample_list_path, "w", encoding="utf-8") as f:
    for path in sample_archive_paths:
        f.write(path + "\n")

print("Saved sample list:", sample_list_path)
print("Number of files to extract:", len(sample_archive_paths))

Saved sample list: /content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/sample_metadata_files_to_extract.txt
Number of files to extract: 1000

In [57]:
from pathlib import Path

EXTRACTED_METADATA_SAMPLE = REPO_CODE / "Post_metadata_sample_extracted"
EXTRACTED_METADATA_SAMPLE.mkdir(exist_ok=True)

print(EXTRACTED_METADATA_SAMPLE)
print(EXTRACTED_METADATA_SAMPLE.exists())

/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/Post_metadata_sample_extracted
True

In [58]:
import subprocess

cmd = [
    "7z",
    "x",
    str(POSTS_INFO_ZIP),
    "@" + str(sample_list_path),
    "-o" + str(EXTRACTED_METADATA_SAMPLE),
    "-y"
]

print("Running command:")
print(cmd)

result = subprocess.run(cmd, capture_output=True, text=True)

print("STDOUT:")
print(result.stdout[:3000])

print("STDERR:")
print(result.stderr[:3000])

print("Return code:", result.returncode)

Running command:
['7z', 'x', '/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.zip', '@/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/sample_metadata_files_to_extract.txt', '-o/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/Post_metadata_sample_extracted', '-y']
STDOUT:

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Xeon(R) CPU @ 2.20GHz (406F0),ASM,AES-NI)

Scanning the drive for archives:
1 file, 1256261830 bytes (1199 MiB)

Extracting archive: /content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.zip
--
Path = /content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.zip
Type = zip
Physical Size = 1256261830
Embedded Stub Size = 4
64-bit = +
Total Physical Size = 39910967483
Multivolume = +
Volume Index = 18
Volumes = 19

Everything is Ok

Files: 1000
Size:       15553985
Compressed: 39910967483

STDERR:

Return code: 0

In [59]:
sample_metadata_files = (
    list(EXTRACTED_METADATA_SAMPLE.rglob("*.info"))
    + list(EXTRACTED_METADATA_SAMPLE.rglob("*.json"))
)

print("Extracted metadata files:", len(sample_metadata_files))
print(sample_metadata_files[:5])

Extracted metadata files: 1000
[PosixPath('/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/Post_metadata_sample_extracted/info/beckilw_sw-1684125244807239621.info'), PosixPath('/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/Post_metadata_sample_extracted/info/archilovers-1966283174661250572.info'), PosixPath('/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/Post_metadata_sample_extracted/info/laviniaaioana-1892733406089983442.info'), PosixPath('/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/Post_metadata_sample_extracted/info/notjustamumof2-1861977278444228346.info'), PosixPath('/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/Post_metadata_sample_extracted/info/thechristinakay-1548033680911884321.info')]

In [60]:
import json

sample_file = sample_metadata_files[0]

print(sample_file)

with open(sample_file, "r", encoding="utf-8", errors="replace") as f:
    sample_data = json.load(f)

print(type(sample_data))
print(sample_data.keys())

/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/Post_metadata_sample_extracted/info/beckilw_sw-1684125244807239621.info
<class 'dict'>
dict_keys(['gating_info', 'viewer_can_reshare', 'display_resources', 'viewer_in_photo_of_you', 'viewer_has_saved_to_collection', 'viewer_has_saved', 'owner', 'viewer_has_liked', 'id', 'should_log_client_event', 'edge_media_preview_like', 'edge_media_to_tagged_user', 'dimensions', '__typename', 'location', 'shortcode', 'is_ad', 'caption_is_edited', 'edge_media_to_parent_comment', 'media_preview', 'taken_at_timestamp', 'edge_media_to_caption', 'tracking_token', 'has_ranked_comments', 'display_url', 'edge_web_media_to_related_media', 'edge_media_preview_comment', 'comments_disabled', 'edge_media_to_sponsor_user', 'accessibility_caption', 'is_video'])

In [61]:
import json

print(json.dumps(sample_data, indent=2)[:3000])

{
  "gating_info": null,
  "viewer_can_reshare": true,
  "display_resources": [
    {
      "src": "https://scontent-lax3-1.cdninstagram.com/vp/a4e28f66221af03382469542660d9617/5DA9611C/t51.2885-15/sh0.08/e35/s640x640/26156580_544005902617468_5029808145619222528_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com",
      "config_width": 640,
      "config_height": 640
    },
    {
      "src": "https://scontent-lax3-1.cdninstagram.com/vp/1f49ea763af304914e0ab6a85f7a7c07/5DA3081C/t51.2885-15/sh0.08/e35/s750x750/26156580_544005902617468_5029808145619222528_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com",
      "config_width": 750,
      "config_height": 750
    },
    {
      "src": "https://scontent-lax3-1.cdninstagram.com/vp/0483ef0a397a594cd0115f19ca1e2b55/5DBF81F9/t51.2885-15/e35/26156580_544005902617468_5029808145619222528_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com",
      "config_width": 1080,
      "config_height": 1080
    }
  ],
  "viewer_in_photo_of_you": false,
  "viewer_has_saved_to_collection": false,
  "viewer_has_saved": false,
  "owner": {
    "username": "beckilw_sw",
    "is_unpublished": false,
    "requested_by_viewer": false,
    "followed_by_viewer": false,
    "has_blocked_viewer": false,
    "profile_pic_url": "https://scontent-lax3-1.cdninstagram.com/vp/2afb9d62cf2b03f27b956835f55383d5/5DA7E164/t51.2885-19/s150x150/42434642_437261140399778_5529963009998323712_n.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com",
    "full_name": "Becki",
    "blocked_by_viewer": false,
    "is_verified": false,
    "id": "1989118268",
    "is_private": false
  },
  "viewer_has_liked": false,
  "id": "1684125244807239621",
  "should_log_client_event": false,
  "edge_media_preview_like": {
    "count": 182,
    "edges": []
  },
  "edge_media_to_tagged_user": {
    "edges": []
  },
  "dimensions": {
    "width": 1080,
    "height": 1080
  },
  "__typename": "GraphImage",
  "location": null,
  "shortcode": "BdfNvy-ANfF",
  "is_ad": false,
  "caption_is_edited": false,
  "edge_media_to_parent_comment": {
    "count": 9,
    "page_info": {
      "end_cursor": null,
      "has_next_page": false
    },
    "edges": [
      {
        "node": {
          "text": "Donughts in my staff room today but I stuck to my banana. \ud83c\udf4c I will get to target. \ud83c\udfaf",
          "created_at": 1514993162,
          "did_report_as_spam": false,
          "edge_liked_by": {
            "count": 1
          },
          "owner": {
            "username": "clairebeared73",
            "profile_pic_url": "https://scontent-lax3-1.cdninstagram.com/vp/8b320bd8a44e736f58e597b62b04e5ca/5DB6FF6A/t51.2885-19/11821672_1480915345542644_1637857994_a.jpg?_nc_ht=scontent-lax3-1.cdninstagram.com",
            "is_verified": false,
            "id": "349169153"
          },
          "viewer_has_liked": false,
          "edge_threaded_comments": {
            "count": 1,
            "page_info": {
              "end_cursor": null,
              "has_next_page": false

In [63]:
sample_data.keys()

dict_keys(['gating_info', 'viewer_can_reshare', 'display_resources', 'viewer_in_photo_of_you', 'viewer_has_saved_to_collection', 'viewer_has_saved', 'owner', 'viewer_has_liked', 'id', 'should_log_client_event', 'edge_media_preview_like', 'edge_media_to_tagged_user', 'dimensions', '__typename', 'location', 'shortcode', 'is_ad', 'caption_is_edited', 'edge_media_to_parent_comment', 'media_preview', 'taken_at_timestamp', 'edge_media_to_caption', 'tracking_token', 'has_ranked_comments', 'display_url', 'edge_web_media_to_related_media', 'edge_media_preview_comment', 'comments_disabled', 'edge_media_to_sponsor_user', 'accessibility_caption', 'is_video'])

In [64]:
for p in sample_metadata_files[:10]:
    print(p.name)

beckilw_sw-1684125244807239621.info
archilovers-1966283174661250572.info
laviniaaioana-1892733406089983442.info
notjustamumof2-1861977278444228346.info
thechristinakay-1548033680911884321.info
jasonnaylor-2018247528004639299.info
mrthreepiece-1593726884489821885.info
willows_den-1858788687819702788.info
uhmlady-1464273234106453793.info
inesjoly-1718391610176599945.info

In [65]:
import re
import pandas as pd

metadata_paths_df = pd.DataFrame({
    "metadata_path": [str(p) for p in sample_metadata_files],
    "extracted_file_name": [p.name for p in sample_metadata_files]
})

def extract_json_name(filename):
    match = re.search(r"(\d+\.info)$", filename)
    if match:
        return match.group(1)
    match = re.search(r"(\d+\.json)$", filename)
    if match:
        return match.group(1)
    return filename

metadata_paths_df["json_postmetadata_file_name"] = metadata_paths_df["extracted_file_name"].apply(extract_json_name)

metadata_paths_df.head()

,metadata_path,extracted_file_name,json_postmetadata_file_name
0,/content/drive/MyDrive/DSCI351/Class Project/D...,beckilw_sw-1684125244807239621.info,1684125244807239621.info
1,/content/drive/MyDrive/DSCI351/Class Project/D...,archilovers-1966283174661250572.info,1966283174661250572.info
2,/content/drive/MyDrive/DSCI351/Class Project/D...,laviniaaioana-1892733406089983442.info,1892733406089983442.info
3,/content/drive/MyDrive/DSCI351/Class Project/D...,notjustamumof2-1861977278444228346.info,1861977278444228346.info
4,/content/drive/MyDrive/DSCI351/Class Project/D...,thechristinakay-1548033680911884321.info,1548033680911884321.info

In [66]:
metadata_paths_df[["extracted_file_name", "json_postmetadata_file_name"]].head(20)

                         extracted_file_name json_postmetadata_file_name
0        beckilw_sw-1684125244807239621.info    1684125244807239621.info
1       archilovers-1966283174661250572.info    1966283174661250572.info
2     laviniaaioana-1892733406089983442.info    1892733406089983442.info
3    notjustamumof2-1861977278444228346.info    1861977278444228346.info
4   thechristinakay-1548033680911884321.info    1548033680911884321.info
5       jasonnaylor-2018247528004639299.info    2018247528004639299.info
6      mrthreepiece-1593726884489821885.info    1593726884489821885.info
7       willows_den-1858788687819702788.info    1858788687819702788.info
8           uhmlady-1464273234106453793.info    1464273234106453793.info
9          inesjoly-1718391610176599945.info    1718391610176599945.info
10   audreymadstowe-1984360583001290713.info    1984360583001290713.info
11   amandaseghetti-1867586031717905958.info    1867586031717905958.info
12      wideopenmag-1997884098996365713.info    1997884098996365713.info
13      fashaddicti-2018656901579756677.info    2018656901579756677.info
14       marylublog-1445132340660785927.info    1445132340660785927.info
15         carafit3-1804658090069443886.info    1804658090069443886.info
16   selintufanoglu-1873209360836279415.info    1873209360836279415.info
17     thefoodmedic-1879067642178937444.info    1879067642178937444.info
18      scitec__uae-1937710989644359140.info    1937710989644359140.info
19       tanyas1288-1384463699196422338.info    1384463699196422338.info

In [68]:
sample_metadata_to_load = json_mapping_clean.merge(
    metadata_paths_df,
    on="json_postmetadata_file_name",
    how="inner"
)

print("Sample metadata paths:", metadata_paths_df.shape)
print("Matched with mapping:", sample_metadata_to_load.shape)

sample_metadata_to_load.head()

Sample metadata paths: (1000, 3)
Matched with mapping: (979, 5)

,influencer_name,json_postmetadata_file_name,image_file_name,metadata_path,extracted_file_name
0,00_rocketgirl,1947481524022722994.info,['1947481524022722994.jpg'],/content/drive/MyDrive/DSCI351/Class Project/D...,00_rocketgirl-1947481524022722994.info
1,1crazyhousetips,1322829373401528064.info,['1322829373401528064.jpg'],/content/drive/MyDrive/DSCI351/Class Project/D...,1crazyhousetips-1322829373401528064.info
2,1liz_vader3,1985912174901367075.info,['1985912174901367075.jpg'],/content/drive/MyDrive/DSCI351/Class Project/D...,1liz_vader3-1985912174901367075.info
3,2marriedgeeks,2036707497192226578.info,['2036707497192226578.jpg'],/content/drive/MyDrive/DSCI351/Class Project/D...,2marriedgeeks-2036707497192226578.info
4,9494_ho,2007436400653072644.info,"['2007436397448732023.jpg', '20074363974739044...",/content/drive/MyDrive/DSCI351/Class Project/D...,9494_ho-2007436400653072644.info

In [69]:
import json
import re
import pandas as pd
from tqdm import tqdm

def safe_get_count(data, key):
    """
    Handles nested Instagram count fields like:
    edge_media_preview_like: {"count": 182}
    """
    value = data.get(key, {})
    if isinstance(value, dict):
        return value.get("count", 0)
    return 0

def extract_caption(data):
    """
    Captions are usually stored in:
    edge_media_to_caption -> edges -> node -> text
    """
    caption_obj = data.get("edge_media_to_caption", {})
    edges = caption_obj.get("edges", [])

    if len(edges) > 0:
        node = edges[0].get("node", {})
        return node.get("text", "")

    return ""

def extract_location(data):
    location = data.get("location")
    if isinstance(location, dict):
        return location.get("name", None)
    return None

def extract_sponsor_count(data):
    sponsor_obj = data.get("edge_media_to_sponsor_user", {})
    if isinstance(sponsor_obj, dict):
        edges = sponsor_obj.get("edges", [])
        return len(edges)
    return 0

def extract_hashtags(text):
    if not isinstance(text, str):
        return []
    return re.findall(r"#(\w+)", text.lower())

def parse_metadata_file(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            data = json.load(f)
    except Exception:
        return None

    caption = extract_caption(data)

    return {
        "post_id": data.get("id"),
        "owner_username": data.get("owner", {}).get("username") if isinstance(data.get("owner"), dict) else None,
        "shortcode": data.get("shortcode"),
        "likes": safe_get_count(data, "edge_media_preview_like"),
        "comments": safe_get_count(data, "edge_media_to_parent_comment"),
        "preview_comments": safe_get_count(data, "edge_media_preview_comment"),
        "caption": caption,
        "caption_length": len(caption) if isinstance(caption, str) else 0,
        "hashtags": extract_hashtags(caption),
        "num_hashtags": len(extract_hashtags(caption)),
        "timestamp": data.get("taken_at_timestamp"),
        "is_ad": data.get("is_ad", False),
        "sponsor_count": extract_sponsor_count(data),
        "is_video": data.get("is_video", False),
        "post_type": data.get("__typename"),
        "location_name": extract_location(data),
        "width": data.get("dimensions", {}).get("width") if isinstance(data.get("dimensions"), dict) else None,
        "height": data.get("dimensions", {}).get("height") if isinstance(data.get("dimensions"), dict) else None,
    }

In [70]:
metadata_rows = []

for _, row in tqdm(sample_metadata_to_load.iterrows(), total=len(sample_metadata_to_load)):
    parsed = parse_metadata_file(row["metadata_path"])

    if parsed is None:
        continue

    parsed["influencer_name"] = row["influencer_name"]
    parsed["json_postmetadata_file_name"] = row["json_postmetadata_file_name"]
    parsed["image_file_name"] = row["image_file_name"]
    parsed["metadata_path"] = row["metadata_path"]
    parsed["extracted_file_name"] = row["extracted_file_name"]

    metadata_rows.append(parsed)

posts_sample_df = pd.DataFrame(metadata_rows)

print(posts_sample_df.shape)
posts_sample_df.head()

100%|██████████| 979/979 [00:05<00:00, 194.51it/s]

(979, 23)

,post_id,owner_username,shortcode,likes,comments,preview_comments,caption,caption_length,hashtags,num_hashtags,...,is_video,post_type,location_name,width,height,influencer_name,json_postmetadata_file_name,image_file_name,metadata_path,extracted_file_name
0,1947481524022722994,00_rocketgirl,BsG2CC-AsGy,117,9,9,12/17/18- Rockets vs Jazz. Just Don shorts (no...,219,"[rockets, houstonrockets, ootd, vintagenba, ww...",6,...,False,GraphImage,None,1080,1350,00_rocketgirl,1947481524022722994.info,['1947481524022722994.jpg'],/content/drive/MyDrive/DSCI351/Class Project/D...,00_rocketgirl-1947481524022722994.info
1,1322829373401528064,1crazyhousetips,BJbok50DPcA,168,21,21,This organization system for your fridge is pe...,184,"[knowyourfood, geniusidea, organizeyourlife, r...",6,...,False,GraphImage,None,1080,1080,1crazyhousetips,1322829373401528064.info,['1322829373401528064.jpg'],/content/drive/MyDrive/DSCI351/Class Project/D...,1crazyhousetips-1322829373401528064.info
2,1985912174901367075,1liz_vader3,BuPYJnsHpEj,975,45,45,Say it again Darling~ 👄\n👄\n👄\n👄\n👄\n👄\n👄 \n#f...,181,"[forevermood, freddymercury, queen, light, gir...",17,...,False,GraphImage,None,1080,1350,1liz_vader3,1985912174901367075.info,['1985912174901367075.jpg'],/content/drive/MyDrive/DSCI351/Class Project/D...,1liz_vader3-1985912174901367075.info
3,2036707497192226578,2marriedgeeks,BxD1q2BhH8S,108,20,20,May the Fourth be with you! This is one of my ...,632,"[maythefourthbewithyou, maythe4thbewithyou, st...",21,...,False,GraphImage,None,1080,1080,2marriedgeeks,2036707497192226578.info,['2036707497192226578.jpg'],/content/drive/MyDrive/DSCI351/Class Project/D...,2marriedgeeks-2036707497192226578.info
4,2007436400653072644,9494_ho,Bvb2MVCHXkE,3079,1,1,🎀\n#홈에스테틱 으로 꼭 추천하고 싶은#GD11앰플\n.\n.\n#GD11 는 #...,346,"[홈에스테틱, gd11앰플, gd11, 줄기세포앰플, 홈케어, 지디일레븐, 줄기세포...",23,...,False,GraphSidecar,None,750,750,9494_ho,2007436400653072644.info,"['2007436397448732023.jpg', '20074363974739044...",/content/drive/MyDrive/DSCI351/Class Project/D...,9494_ho-2007436400653072644.info

In [71]:
posts_sample_df[[
    "influencer_name",
    "post_id",
    "likes",
    "comments",
    "caption",
    "num_hashtags",
    "timestamp",
    "is_ad",
    "is_video",
    "post_type"
]].head()

,influencer_name,post_id,likes,comments,caption,num_hashtags,timestamp,is_ad,is_video,post_type
0,00_rocketgirl,1947481524022722994,117,9,12/17/18- Rockets vs Jazz. Just Don shorts (no...,6,1546377910,False,False,GraphImage
1,1crazyhousetips,1322829373401528064,168,21,This organization system for your fridge is pe...,6,1471913571,False,False,GraphImage
2,1liz_vader3,1985912174901367075,975,45,Say it again Darling~ 👄\n👄\n👄\n👄\n👄\n👄\n👄 \n#f...,17,1550959201,False,False,GraphImage
3,2marriedgeeks,2036707497192226578,108,20,May the Fourth be with you! This is one of my ...,21,1557014475,False,False,GraphImage
4,9494_ho,2007436400653072644,3079,1,🎀\n#홈에스테틱 으로 꼭 추천하고 싶은#GD11앰플\n.\n.\n#GD11 는 #...,23,1553525088,False,False,GraphSidecar

In [72]:
posts_sample_df[[
    "influencer_name",
    "post_id",
    "likes",
    "comments",
    "caption",
    "timestamp"
]].isna().sum()

influencer_name    0
post_id            0
likes              0
comments           0
caption            0
timestamp          0
dtype: int64

In [73]:
posts_sample_df[["likes", "comments", "caption_length", "num_hashtags"]].describe()

               likes     comments  caption_length  num_hashtags
count     979.000000   979.000000      979.000000    979.000000
mean     3963.550562    42.170582      313.978550      8.009193
std     25392.589516   178.442382      308.621843     10.229919
min         4.000000     0.000000        0.000000      0.000000
25%       145.500000     2.000000       74.500000      0.000000
50%       453.000000    11.000000      216.000000      3.000000
75%      1406.000000    39.000000      462.000000     13.000000
max    507922.000000  4892.000000     2189.000000     34.000000

In [74]:
posts_sample_df["datetime"] = pd.to_datetime(
    posts_sample_df["timestamp"],
    unit="s",
    errors="coerce"
)

posts_sample_df["hour"] = posts_sample_df["datetime"].dt.hour
posts_sample_df["day_of_week"] = posts_sample_df["datetime"].dt.day_name()
posts_sample_df["month"] = posts_sample_df["datetime"].dt.month

def hour_bucket(hour):
    if pd.isna(hour):
        return "unknown_time"
    elif 5 <= hour < 12:
        return "morning"
    elif 12 <= hour < 17:
        return "afternoon"
    elif 17 <= hour < 22:
        return "evening"
    else:
        return "night"

posts_sample_df["time_bucket"] = posts_sample_df["hour"].apply(hour_bucket)

posts_sample_df[["timestamp", "datetime", "hour", "time_bucket", "day_of_week"]].head()

    timestamp            datetime  hour time_bucket day_of_week
0  1546377910 2019-01-01 21:25:10    21     evening     Tuesday
1  1471913571 2016-08-23 00:52:51     0       night     Tuesday
2  1550959201 2019-02-23 22:00:01    22       night    Saturday
3  1557014475 2019-05-05 00:01:15     0       night      Sunday
4  1553525088 2019-03-25 14:44:48    14   afternoon      Monday

In [75]:
def caption_bucket(length):
    if pd.isna(length):
        return "unknown_caption"
    elif length < 80:
        return "short_caption"
    elif length < 200:
        return "medium_caption"
    else:
        return "long_caption"

def hashtag_bucket(n):
    if pd.isna(n):
        return "unknown_hashtags"
    elif n == 0:
        return "no_hashtags"
    elif n <= 3:
        return "few_hashtags"
    else:
        return "many_hashtags"

posts_sample_df["caption_bucket"] = posts_sample_df["caption_length"].apply(caption_bucket)
posts_sample_df["hashtag_bucket"] = posts_sample_df["num_hashtags"].apply(hashtag_bucket)
posts_sample_df["ad_bucket"] = posts_sample_df["is_ad"].apply(lambda x: "ad" if x else "not_ad")
posts_sample_df["media_bucket"] = posts_sample_df["is_video"].apply(lambda x: "video" if x else "image")

posts_sample_df["strategy"] = (
    posts_sample_df["time_bucket"].astype(str)
    + " + " + posts_sample_df["caption_bucket"].astype(str)
    + " + " + posts_sample_df["hashtag_bucket"].astype(str)
    + " + " + posts_sample_df["ad_bucket"].astype(str)
    + " + " + posts_sample_df["media_bucket"].astype(str)
)

posts_sample_df[[
    "influencer_name",
    "likes",
    "comments",
    "caption_bucket",
    "hashtag_bucket",
    "time_bucket",
    "ad_bucket",
    "media_bucket",
    "strategy"
]].head()

,influencer_name,likes,comments,caption_bucket,hashtag_bucket,time_bucket,ad_bucket,media_bucket,strategy
0,00_rocketgirl,117,9,long_caption,many_hashtags,evening,not_ad,image,evening + long_caption + many_hashtags + not_a...
1,1crazyhousetips,168,21,medium_caption,many_hashtags,night,not_ad,image,night + medium_caption + many_hashtags + not_a...
2,1liz_vader3,975,45,medium_caption,many_hashtags,night,not_ad,image,night + medium_caption + many_hashtags + not_a...
3,2marriedgeeks,108,20,long_caption,many_hashtags,night,not_ad,image,night + long_caption + many_hashtags + not_ad ...
4,9494_ho,3079,1,long_caption,many_hashtags,afternoon,not_ad,image,afternoon + long_caption + many_hashtags + not...

In [76]:
influencers_df = pd.read_csv(INFLUENCERS, sep="\t", engine="python")

print(influencers_df.shape)
influencers_df.head()

(33936, 5)

,Username,Category,#Followers,#Followees,#Posts
0,==============================================...,None,NaN,NaN,NaN
1,makeupbynvs,beauty,1432.0,1089.0,363.0
2,jaquelinevandoski,beauty,137600.0,548.0,569.0
3,anisaartistry,beauty,64644.0,289.0,391.0
4,rubina_muartistry,beauty,496406.0,742.0,887.0

In [77]:
influencers_df = pd.read_csv(INFLUENCERS, sep=None, engine="python")

print(influencers_df.shape)
influencers_df.head()

(33936, 5)

,Username,Category,#Followers,#Followees,#Posts
0,==============================================...,None,NaN,NaN,NaN
1,makeupbynvs,beauty,1432.0,1089.0,363.0
2,jaquelinevandoski,beauty,137600.0,548.0,569.0
3,anisaartistry,beauty,64644.0,289.0,391.0
4,rubina_muartistry,beauty,496406.0,742.0,887.0

In [78]:
influencers_df.columns = [c.strip() for c in influencers_df.columns]

influencers_df = influencers_df.rename(columns={
    "Username": "influencer_name",
    "Category": "category",
    "#Followers": "followers",
    "#Followees": "followees",
    "#Posts": "total_posts"
})

influencers_df.head()

,influencer_name,category,followers,followees,total_posts
0,==============================================...,None,NaN,NaN,NaN
1,makeupbynvs,beauty,1432.0,1089.0,363.0
2,jaquelinevandoski,beauty,137600.0,548.0,569.0
3,anisaartistry,beauty,64644.0,289.0,391.0
4,rubina_muartistry,beauty,496406.0,742.0,887.0

In [79]:
influencers_df.drop(0)

         influencer_name category  followers  followees  total_posts
1            makeupbynvs   beauty     1432.0     1089.0        363.0
2      jaquelinevandoski   beauty   137600.0      548.0        569.0
3          anisaartistry   beauty    64644.0      289.0        391.0
4      rubina_muartistry   beauty   496406.0      742.0        887.0
5            beautyxabbi   beauty     2050.0     1423.0        751.0
...                  ...      ...        ...        ...          ...
33931         alingzhang    other     4597.0      881.0        365.0
33932        flower.jini    other    27093.0     1599.0        664.0
33933     ester_starling    other    20621.0       23.0        783.0
33934       lovely___yul    other    12381.0      811.0        223.0
33935          sara_agos    other     1277.0      790.0        311.0

[33935 rows x 5 columns]

In [80]:
posts_base_sample_df = posts_sample_df.merge(
    influencers_df,
    on="influencer_name",
    how="left"
)

print(posts_sample_df.shape)
print(posts_base_sample_df.shape)

posts_base_sample_df[[
    "influencer_name",
    "category",
    "followers",
    "likes",
    "comments",
    "strategy"
]].head()

(979, 33)
(979, 37)

,influencer_name,category,followers,likes,comments,strategy
0,00_rocketgirl,other,6453.0,117,9,evening + long_caption + many_hashtags + not_a...
1,1crazyhousetips,other,13371.0,168,21,night + medium_caption + many_hashtags + not_a...
2,1liz_vader3,beauty,14032.0,975,45,night + medium_caption + many_hashtags + not_a...
3,2marriedgeeks,family,1293.0,108,20,night + long_caption + many_hashtags + not_ad ...
4,9494_ho,other,130416.0,3079,1,afternoon + long_caption + many_hashtags + not...

In [81]:
posts_base_sample_df["followers"].isna().sum()

np.int64(0)

In [82]:
import numpy as np

posts_base_sample_df["likes"] = pd.to_numeric(posts_base_sample_df["likes"], errors="coerce").fillna(0)
posts_base_sample_df["comments"] = pd.to_numeric(posts_base_sample_df["comments"], errors="coerce").fillna(0)
posts_base_sample_df["followers"] = pd.to_numeric(posts_base_sample_df["followers"], errors="coerce")

# Avoid divide-by-zero issues
posts_base_sample_df = posts_base_sample_df[posts_base_sample_df["followers"].notna()]
posts_base_sample_df = posts_base_sample_df[posts_base_sample_df["followers"] > 0]

posts_base_sample_df["raw_engagement"] = (
    posts_base_sample_df["likes"] + 2 * posts_base_sample_df["comments"]
)

posts_base_sample_df["engagement_rate"] = (
    posts_base_sample_df["raw_engagement"] / posts_base_sample_df["followers"]
)

posts_base_sample_df["log_engagement_score"] = (
    np.log1p(posts_base_sample_df["raw_engagement"]) / np.log1p(posts_base_sample_df["followers"])
)

posts_base_sample_df[[
    "influencer_name",
    "followers",
    "likes",
    "comments",
    "raw_engagement",
    "engagement_rate",
    "log_engagement_score",
    "strategy"
]].head()

,influencer_name,followers,likes,comments,raw_engagement,engagement_rate,log_engagement_score,strategy
0,00_rocketgirl,6453.0,117,9,135,0.020921,0.560009,evening + long_caption + many_hashtags + not_a...
1,1crazyhousetips,13371.0,168,21,210,0.015706,0.563299,night + medium_caption + many_hashtags + not_a...
2,1liz_vader3,14032.0,975,45,1065,0.075898,0.730081,night + medium_caption + many_hashtags + not_a...
3,2marriedgeeks,1293.0,108,20,148,0.114462,0.698339,night + long_caption + many_hashtags + not_ad ...
4,9494_ho,130416.0,3079,1,3081,0.023624,0.682034,afternoon + long_caption + many_hashtags + not...

In [83]:
base_sample_path = REPO_CODE / "data_processed" / "posts_base_sample.parquet"
base_sample_path.parent.mkdir(exist_ok=True)

posts_base_sample_df.to_parquet(base_sample_path, index=False)

print("Saved base sample to:", base_sample_path)
print(posts_base_sample_df.shape)

Saved base sample to: /content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/data_processed/posts_base_sample.parquet
(979, 40)

In [84]:
strategy_scores = (
    posts_base_sample_df
    .groupby("strategy")
    .agg(
        post_count=("strategy", "count"),
        avg_engagement=("log_engagement_score", "mean"),
        avg_likes=("likes", "mean"),
        avg_comments=("comments", "mean")
    )
    .reset_index()
    .sort_values("avg_engagement", ascending=False)
)

strategy_scores.head(10)

,strategy,post_count,avg_engagement,avg_likes,avg_comments
20,morning + long_caption + no_hashtags + not_ad ...,10,0.725977,26438.200000,131.300000
31,night + medium_caption + no_hashtags + not_ad ...,19,0.698788,3693.842105,58.789474
11,evening + long_caption + no_hashtags + not_ad ...,28,0.685935,2267.500000,44.178571
7,afternoon + short_caption + many_hashtags + no...,4,0.685513,761.000000,4.750000
18,morning + long_caption + few_hashtags + not_ad...,14,0.676440,2642.571429,51.785714
0,afternoon + long_caption + few_hashtags + not_...,20,0.656525,2130.900000,54.750000
26,night + long_caption + few_hashtags + not_ad +...,25,0.656192,2368.520000,27.000000
17,evening + short_caption + no_hashtags + not_ad...,55,0.654520,11247.000000,114.854545
2,afternoon + long_caption + no_hashtags + not_a...,14,0.653410,1095.857143,59.785714
15,evening + short_caption + few_hashtags + not_a...,25,0.653288,11153.480000,33.480000

In [85]:
strategy_scores_filtered = strategy_scores[strategy_scores["post_count"] >= 10]

strategy_scores_filtered.head(10)

,strategy,post_count,avg_engagement,avg_likes,avg_comments
20,morning + long_caption + no_hashtags + not_ad ...,10,0.725977,26438.200000,131.300000
31,night + medium_caption + no_hashtags + not_ad ...,19,0.698788,3693.842105,58.789474
11,evening + long_caption + no_hashtags + not_ad ...,28,0.685935,2267.500000,44.178571
18,morning + long_caption + few_hashtags + not_ad...,14,0.676440,2642.571429,51.785714
0,afternoon + long_caption + few_hashtags + not_...,20,0.656525,2130.900000,54.750000
26,night + long_caption + few_hashtags + not_ad +...,25,0.656192,2368.520000,27.000000
17,evening + short_caption + no_hashtags + not_ad...,55,0.654520,11247.000000,114.854545
2,afternoon + long_caption + no_hashtags + not_a...,14,0.653410,1095.857143,59.785714
15,evening + short_caption + few_hashtags + not_a...,25,0.653288,11153.480000,33.480000
14,evening + medium_caption + no_hashtags + not_a...,23,0.649209,4568.434783,84.913043

# build first baseline recommender

In [86]:
def recommend_global_strategies(strategy_scores, k=5, min_posts=10):
    """
    Recommends the highest-performing content strategies overall.
    This is our first baseline recommender.
    """
    filtered = strategy_scores[strategy_scores["post_count"] >= min_posts]

    return filtered.sort_values(
        "avg_engagement",
        ascending=False
    ).head(k)

recommend_global_strategies(strategy_scores, k=5, min_posts=10)

,strategy,post_count,avg_engagement,avg_likes,avg_comments
20,morning + long_caption + no_hashtags + not_ad ...,10,0.725977,26438.200000,131.300000
31,night + medium_caption + no_hashtags + not_ad ...,19,0.698788,3693.842105,58.789474
11,evening + long_caption + no_hashtags + not_ad ...,28,0.685935,2267.500000,44.178571
18,morning + long_caption + few_hashtags + not_ad...,14,0.676440,2642.571429,51.785714
0,afternoon + long_caption + few_hashtags + not_...,20,0.656525,2130.900000,54.750000

In [87]:
category_strategy_scores = (
    posts_base_sample_df
    .groupby(["category", "strategy"])
    .agg(
        post_count=("strategy", "count"),
        avg_engagement=("log_engagement_score", "mean"),
        avg_likes=("likes", "mean"),
        avg_comments=("comments", "mean")
    )
    .reset_index()
    .sort_values(["category", "avg_engagement"], ascending=[True, False])
)

category_strategy_scores.head(10)

,category,strategy,post_count,avg_engagement,avg_likes,avg_comments
3,beauty,afternoon + medium_caption + no_hashtags + not...,1,0.817013,3727.0,76.0
11,beauty,morning + long_caption + few_hashtags + not_ad...,1,0.788481,7349.0,139.0
7,beauty,evening + long_caption + no_hashtags + not_ad ...,2,0.743678,2756.5,60.0
6,beauty,evening + long_caption + many_hashtags + not_a...,1,0.710001,963.0,22.0
13,beauty,morning + medium_caption + few_hashtags + not_...,1,0.686970,598.0,93.0
9,beauty,evening + medium_caption + many_hashtags + not...,1,0.678239,479.0,50.0
2,beauty,afternoon + medium_caption + many_hashtags + n...,1,0.672446,725.0,22.0
5,beauty,evening + long_caption + few_hashtags + not_ad...,2,0.672316,17149.5,98.0
14,beauty,morning + medium_caption + many_hashtags + not...,1,0.661686,252.0,87.0
18,beauty,night + medium_caption + no_hashtags + not_ad ...,1,0.659418,12261.0,147.0

In [88]:
def recommend_by_category(category, category_strategy_scores, k=5, min_posts=3):
    """
    Recommends strategies that performed well for influencers in the same category.
    """
    filtered = category_strategy_scores[
        (category_strategy_scores["category"] == category)
        & (category_strategy_scores["post_count"] >= min_posts)
    ]

    return filtered.sort_values(
        "avg_engagement",
        ascending=False
    ).head(k)

recommend_by_category("fashion", category_strategy_scores, k=5, min_posts=3)

,category,strategy,post_count,avg_engagement,avg_likes,avg_comments
69,fashion,morning + long_caption + no_hashtags + not_ad ...,3,0.749439,81991.666667,324.333333
61,fashion,evening + long_caption + no_hashtags + not_ad ...,11,0.715419,2990.272727,48.545455
63,fashion,evening + medium_caption + many_hashtags + not...,5,0.711220,2542.200000,12.200000
80,fashion,night + medium_caption + no_hashtags + not_ad ...,9,0.707219,2860.000000,45.888889
64,fashion,evening + medium_caption + no_hashtags + not_a...,11,0.700787,7714.181818,145.272727

In [89]:
posts_base_sample_df["category"].value_counts()

category
fashion     338
other       175
food        121
travel      113
family      112
beauty       39
interior     33
fitness      27
pet          21
Name: count, dtype: int64

In [90]:
recommend_by_category("food", category_strategy_scores, k=5, min_posts=3)
recommend_by_category("travel", category_strategy_scores, k=5, min_posts=3)
recommend_by_category("fitness", category_strategy_scores, k=5, min_posts=3)

,category,strategy,post_count,avg_engagement,avg_likes,avg_comments
99,fitness,night + short_caption + no_hashtags + not_ad +...,3,0.767914,180473.666667,99.666667
89,fitness,evening + short_caption + no_hashtags + not_ad...,3,0.676948,873.000000,9.333333
87,fitness,evening + long_caption + many_hashtags + not_a...,4,0.667264,855.750000,122.750000

In [91]:
print("Posts:", len(posts_base_sample_df))
print("Unique influencers:", posts_base_sample_df["influencer_name"].nunique())
print("Unique strategies:", posts_base_sample_df["strategy"].nunique())

posts_per_influencer = posts_base_sample_df["influencer_name"].value_counts()
print(posts_per_influencer.describe())

posts_per_influencer.head(20)

Posts: 979
Unique influencers: 965
Unique strategies: 35
count    965.000000
mean       1.014508
std        0.119633
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        2.000000
Name: count, dtype: float64

influencer_name
laughingspatula           2
brunoguedes               2
alexcurtiswellness        2
selintufanoglu            2
swearbycare               2
ourlifeatthewhitehouse    2
tashaleelyn               2
domestikateblog           2
ohdeardrea                2
susannebarnekow           2
petroffdaily              2
valentina_stee            2
graziauk                  2
guipintto                 2
omgitsmonii               1
oliviadbuck               1
olivia_in_korea           1
obie_boy                  1
noz_omi                   1
notjustamumof2            1
Name: count, dtype: int64

In [92]:
interaction_matrix = posts_base_sample_df.pivot_table(
    index="influencer_name",
    columns="strategy",
    values="log_engagement_score",
    aggfunc="mean"
)

print(interaction_matrix.shape)

non_missing = interaction_matrix.notna().sum().sum()
total_cells = interaction_matrix.shape[0] * interaction_matrix.shape[1]
density = non_missing / total_cells

print("Non-missing interactions:", non_missing)
print("Total cells:", total_cells)
print("Matrix density:", density)

(965, 35)
Non-missing interactions: 975
Total cells: 33775
Matrix density: 0.028867505551443375

In [93]:
interaction_matrix_filled = interaction_matrix.fillna(0)

interaction_matrix_filled.head()

strategy,afternoon + long_caption + few_hashtags + not_ad + image,afternoon + long_caption + many_hashtags + not_ad + image,afternoon + long_caption + no_hashtags + not_ad + image,afternoon + medium_caption + few_hashtags + not_ad + image,afternoon + medium_caption + many_hashtags + not_ad + image,afternoon + medium_caption + no_hashtags + not_ad + image,afternoon + short_caption + few_hashtags + not_ad + image,afternoon + short_caption + many_hashtags + not_ad + image,afternoon + short_caption + no_hashtags + not_ad + image,evening + long_caption + few_hashtags + not_ad + image,...,morning + short_caption + no_hashtags + not_ad + image,night + long_caption + few_hashtags + not_ad + image,night + long_caption + many_hashtags + not_ad + image,night + long_caption + no_hashtags + not_ad + image,night + medium_caption + few_hashtags + not_ad + image,night + medium_caption + many_hashtags + not_ad + image,night + medium_caption + no_hashtags + not_ad + image,night + short_caption + few_hashtags + not_ad + image,night + short_caption + many_hashtags + not_ad + image,night + short_caption + no_hashtags + not_ad + image
influencer_name,,,,,,,,,,,,,,,,,,,,,
00_rocketgirl,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1crazyhousetips,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.563299,0.0,0.0,0.0,0.0
1liz_vader3,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.730081,0.0,0.0,0.0,0.0
2marriedgeeks,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.698339,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
9494_ho,0.0,0.682034,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [94]:
print("Interaction matrix shape:", interaction_matrix.shape)

non_missing = interaction_matrix.notna().sum().sum()
total_cells = interaction_matrix.shape[0] * interaction_matrix.shape[1]
density = non_missing / total_cells

print("Non-missing interactions:", non_missing)
print("Total cells:", total_cells)
print("Matrix density:", density)

posts_per_influencer = posts_base_sample_df["influencer_name"].value_counts()
print(posts_per_influencer.describe())

Interaction matrix shape: (965, 35)
Non-missing interactions: 975
Total cells: 33775
Matrix density: 0.028867505551443375
count    965.000000
mean       1.014508
std        0.119633
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        2.000000
Name: count, dtype: float64

# Ulser based collaborative filtering

In [95]:
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import numpy as np

# Fill missing values with 0 for similarity calculation
interaction_matrix_filled = interaction_matrix.fillna(0)

# Compute user-user similarity
user_similarity = cosine_similarity(interaction_matrix_filled)

user_similarity_df = pd.DataFrame(
    user_similarity,
    index=interaction_matrix_filled.index,
    columns=interaction_matrix_filled.index
)

user_similarity_df.head()

influencer_name,00_rocketgirl,1crazyhousetips,1liz_vader3,2marriedgeeks,9494_ho,9to5chic,__.izu,__lilli,_allsmilesxo,_claudiabella_,...,youluvmeme,yourunicornbabe,yumiilym,zalkaraskaraliev,zampatelmundo,zaras_home,zengrrl,zhureta,zoe.ballerina1,zomatouae
influencer_name,,,,,,,,,,,,,,,,,,,,,
00_rocketgirl,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1crazyhousetips,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1liz_vader3,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2marriedgeeks,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
9494_ho,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [96]:
def recommend_user_based_cf(
    influencer_name,
    interaction_matrix,
    user_similarity_df,
    k=5,
    n_neighbors=10
):
    """
    Recommend strategies for one influencer using user-based collaborative filtering.
    """

    if influencer_name not in interaction_matrix.index:
        return pd.DataFrame({"error": [f"{influencer_name} not found in interaction matrix"]})

    # Similar influencers
    similarities = user_similarity_df[influencer_name].drop(index=influencer_name)
    top_neighbors = similarities.sort_values(ascending=False).head(n_neighbors)

    # Keep only positive similarities
    top_neighbors = top_neighbors[top_neighbors > 0]

    if len(top_neighbors) == 0:
        return pd.DataFrame({"error": ["No similar influencers found"]})

    # Neighbor strategy scores
    neighbor_scores = interaction_matrix.loc[top_neighbors.index]

    # Weighted average score for each strategy
    weighted_scores = neighbor_scores.T.dot(top_neighbors)
    similarity_sum = top_neighbors.sum()

    predicted_scores = weighted_scores / similarity_sum

    # Remove strategies the influencer already has
    already_used = interaction_matrix.loc[influencer_name].dropna().index
    predicted_scores = predicted_scores.drop(index=already_used, errors="ignore")

    recommendations = (
        predicted_scores
        .sort_values(ascending=False)
        .head(k)
        .reset_index()
    )

    recommendations.columns = ["recommended_strategy", "predicted_score"]

    return recommendations

In [97]:
sample_influencer = interaction_matrix.index[0]
sample_influencer

'00_rocketgirl'

In [98]:
recommend_user_based_cf(
    sample_influencer,
    interaction_matrix,
    user_similarity_df,
    k=5,
    n_neighbors=10
)

                                recommended_strategy  predicted_score
0  afternoon + long_caption + few_hashtags + not_...              NaN
1  afternoon + long_caption + many_hashtags + not...              NaN
2  afternoon + long_caption + no_hashtags + not_a...              NaN
3  afternoon + medium_caption + few_hashtags + no...              NaN
4  afternoon + medium_caption + many_hashtags + n...              NaN

In [99]:
posts_base_sample_df["influencer_name"].value_counts().head(10)

influencer_name
laughingspatula           2
brunoguedes               2
alexcurtiswellness        2
selintufanoglu            2
swearbycare               2
ourlifeatthewhitehouse    2
tashaleelyn               2
domestikateblog           2
ohdeardrea                2
susannebarnekow           2
Name: count, dtype: int64

In [100]:
sample_influencer = posts_base_sample_df["influencer_name"].value_counts().index[0]

recommend_user_based_cf(
    sample_influencer,
    interaction_matrix,
    user_similarity_df,
    k=5,
    n_neighbors=10
)

                                recommended_strategy  predicted_score
0  afternoon + long_caption + few_hashtags + not_...              NaN
1  afternoon + long_caption + many_hashtags + not...              NaN
2  afternoon + long_caption + no_hashtags + not_a...              NaN
3  afternoon + medium_caption + few_hashtags + no...              NaN
4  afternoon + medium_caption + many_hashtags + n...              NaN

In [101]:
def show_influencer_history(influencer_name, posts_base_sample_df):
    return (
        posts_base_sample_df[posts_base_sample_df["influencer_name"] == influencer_name]
        [["influencer_name", "category", "likes", "comments", "log_engagement_score", "strategy"]]
        .sort_values("log_engagement_score", ascending=False)
    )

show_influencer_history(sample_influencer, posts_base_sample_df)

,influencer_name,category,likes,comments,log_engagement_score,strategy
456,laughingspatula,food,44,5,0.401396,night + long_caption + many_hashtags + not_ad ...
457,laughingspatula,food,37,1,0.369498,night + short_caption + no_hashtags + not_ad +...

In [102]:
print("Influencer:", sample_influencer)

print("\nInfluencer history:")
display(show_influencer_history(sample_influencer, posts_base_sample_df).head(5))

print("\nGlobal baseline recommendations:")
display(recommend_global_strategies(strategy_scores, k=5, min_posts=10))

print("\nUser-based CF recommendations:")
display(recommend_user_based_cf(sample_influencer, interaction_matrix, user_similarity_df, k=5, n_neighbors=10))

Influencer: laughingspatula

Influencer history:

,influencer_name,category,likes,comments,log_engagement_score,strategy
456,laughingspatula,food,44,5,0.401396,night + long_caption + many_hashtags + not_ad ...
457,laughingspatula,food,37,1,0.369498,night + short_caption + no_hashtags + not_ad +...

Global baseline recommendations:

,strategy,post_count,avg_engagement,avg_likes,avg_comments
20,morning + long_caption + no_hashtags + not_ad ...,10,0.725977,26438.200000,131.300000
31,night + medium_caption + no_hashtags + not_ad ...,19,0.698788,3693.842105,58.789474
11,evening + long_caption + no_hashtags + not_ad ...,28,0.685935,2267.500000,44.178571
18,morning + long_caption + few_hashtags + not_ad...,14,0.676440,2642.571429,51.785714
0,afternoon + long_caption + few_hashtags + not_...,20,0.656525,2130.900000,54.750000

User-based CF recommendations:

                                recommended_strategy  predicted_score
0  afternoon + long_caption + few_hashtags + not_...              NaN
1  afternoon + long_caption + many_hashtags + not...              NaN
2  afternoon + long_caption + no_hashtags + not_a...              NaN
3  afternoon + medium_caption + few_hashtags + no...              NaN
4  afternoon + medium_caption + many_hashtags + n...              NaN

In [103]:
model_path = REPO_CODE / "data_processed"

interaction_matrix.to_parquet(model_path / "interaction_matrix_sample.parquet")
user_similarity_df.to_parquet(model_path / "user_similarity_sample.parquet")

print("Saved interaction matrix and user similarity matrix.")

Saved interaction matrix and user similarity matrix.

# Redo but with 10,0000 metadatafiles now

In [104]:
import random

random.seed(42)

sample_archive_paths_10k = random.sample(archive_paths, 10000)

sample_list_path_10k = REPO_CODE / "sample_metadata_files_to_extract_10k.txt"

with open(sample_list_path_10k, "w", encoding="utf-8") as f:
    for path in sample_archive_paths_10k:
        f.write(path + "\n")

print("Saved 10k sample list to:", sample_list_path_10k)
print("Number of files to extract:", len(sample_archive_paths_10k))
print(sample_archive_paths_10k[:5])

Saved 10k sample list to: /content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/sample_metadata_files_to_extract_10k.txt
Number of files to extract: 10000
['info/tidesofmarch_-1099404304104166728.info', 'info/inesjimm-1940734810297274844.info', 'info/amberhukari-1936628901312938481.info', 'info/themomrant-1907355156573114095.info', 'info/therealalexbertie-1529094180075610157.info']

In [105]:
EXTRACTED_METADATA_10K = REPO_CODE / "Post_metadata_10k_extracted"
EXTRACTED_METADATA_10K.mkdir(exist_ok=True)

print(EXTRACTED_METADATA_10K)
print(EXTRACTED_METADATA_10K.exists())

/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/Post_metadata_10k_extracted
True

In [ ]:
import subprocess

cmd = [
    "7z",
    "x",
    str(POSTS_INFO_ZIP),
    "@" + str(sample_list_path_10k),
    "-o" + str(EXTRACTED_METADATA_10K),
    "-y"
]

print("Running command:")
print(cmd)

result = subprocess.run(cmd, capture_output=True, text=True)

print("STDOUT:")
print(result.stdout[-3000:])

print("STDERR:")
print(result.stderr[-3000:])

print("Return code:", result.returncode)

Running command:
['7z', 'x', '/content/drive/.shortcut-targets-by-id/1ISiSH4-aM6kP_0lKQYejpk1sa6Jei-7e/Instagram influencer dataset/Post_metadata/posts_info.zip', '@/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/sample_metadata_files_to_extract_10k.txt', '-o/content/drive/MyDrive/DSCI351/Class Project/DSCI_Recommender_System_Class_Proj/Post_metadata_10k_extracted', '-y']

In [ ]:
sample_metadata_files_10k = (
    list(EXTRACTED_METADATA_10K.rglob("*.info"))
    + list(EXTRACTED_METADATA_10K.rglob("*.json"))
)

print("Extracted metadata files:", len(sample_metadata_files_10k))
print(sample_metadata_files_10k[:5])

In [ ]:
import re
import pandas as pd

metadata_paths_df_10k = pd.DataFrame({
    "metadata_path": [str(p) for p in sample_metadata_files_10k],
    "extracted_file_name": [p.name for p in sample_metadata_files_10k]
})

def extract_json_name(filename):
    match = re.search(r"(\d+\.info)$", filename)
    if match:
        return match.group(1)
    match = re.search(r"(\d+\.json)$", filename)
    if match:
        return match.group(1)
    return filename

metadata_paths_df_10k["json_postmetadata_file_name"] = (
    metadata_paths_df_10k["extracted_file_name"].apply(extract_json_name)
)

print(metadata_paths_df_10k.shape)
metadata_paths_df_10k.head()

In [ ]:
metadata_to_load_10k = json_mapping_clean.merge(
    metadata_paths_df_10k,
    on="json_postmetadata_file_name",
    how="inner"
)

print("Metadata paths:", metadata_paths_df_10k.shape)
print("Matched with mapping:", metadata_to_load_10k.shape)

metadata_to_load_10k.head()

In [ ]:
metadata_to_load_10k = json_mapping_clean.merge(
    metadata_paths_df_10k,
    on="json_postmetadata_file_name",
    how="inner"
)

In [ ]:
from tqdm import tqdm

metadata_rows_10k = []

for _, row in tqdm(metadata_to_load_10k.iterrows(), total=len(metadata_to_load_10k)):
    parsed = parse_metadata_file(row["metadata_path"])

    if parsed is None:
        continue

    parsed["influencer_name"] = row["influencer_name"]
    parsed["json_postmetadata_file_name"] = row["json_postmetadata_file_name"]
    parsed["image_file_name"] = row["image_file_name"]
    parsed["metadata_path"] = row["metadata_path"]
    parsed["extracted_file_name"] = row["extracted_file_name"]

    metadata_rows_10k.append(parsed)

posts_10k_df = pd.DataFrame(metadata_rows_10k)

print(posts_10k_df.shape)
posts_10k_df.head()